//
//  UIColor+NikReminders.swift
//
//  Generated by Zeplin on 2/29/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved.
//

import UIKit

extension UIColor {
    class func nkrLogotypeBlackColor() -> UIColor {
        return UIColor(white: 0.0, alpha: 1.0)
    }

    class func nkrLogotypeLightColor() -> UIColor {
        return UIColor(white: 0.0, alpha: 0.61)
    }

    class func nkrLogotypeUnderlineLightColor() -> UIColor {
        return UIColor(red: 252.0 / 255.0, green: 84.0 / 255.0, blue: 31.0 / 255.0, alpha: 0.32)
    }

    class func nkrBodyTextOffColor() -> UIColor {
        return UIColor(red: 154.0 / 255.0, green: 153.0 / 255.0, blue: 153.0 / 255.0, alpha: 1.0)
    }

    class func nkrReddishOrangeColor() -> UIColor {
        return UIColor(red: 252.0 / 255.0, green: 85.0 / 255.0, blue: 31.0 / 255.0, alpha: 1.0)
    }

    class func nkrPaleSalmonColor() -> UIColor {
        return UIColor(red: 251.0 / 255.0, green: 192.0 / 255.0, blue: 173.0 / 255.0, alpha: 1.0)
    }
}
